"""Create the complete v0.1 schema.

Revision ID: 20260827_0001
Revises:
Create Date: 2026-08-27 15:17:19.774116
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260827_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="active", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active','disabled')", name=op.f("ck_organizations_organization_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "outbox_messages",
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','published')", name=op.f("ck_outbox_messages_outbox_status")
        ),
        sa.CheckConstraint(
            "publish_attempts >= 0", name=op.f("ck_outbox_messages_outbox_publish_attempts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_id"), "outbox_messages", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_available_at"), "outbox_messages", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_messages_lease_until"), "outbox_messages", ["lease_until"], unique=False
    )
    op.create_index(op.f("ix_outbox_messages_status"), "outbox_messages", ["status"], unique=False)
    op.create_index(op.f("ix_outbox_messages_topic"), "outbox_messages", ["topic"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "api_keys",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("secret_digest", sa.String(length=64), nullable=False),
        sa.Column("digest_key_version", sa.Integer(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("organization_id", "id", name="uq_api_keys_organization_id_id"),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_keys_prefix")),
    )
    op.create_index(
        op.f("ix_api_keys_organization_id"), "api_keys", ["organization_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("safe_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','admin','member')", name=op.f("ck_memberships_membership_role")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "webhook_endpoints",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("verification_hash", sa.String(length=64), nullable=True),
        sa.Column("verification_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_delivery_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending_verification','active','disabled','deleted')",
            name=op.f("ck_webhook_endpoints_endpoint_status"),
        ),
        sa.CheckConstraint(
            "active_delivery_count >= 0 AND active_delivery_count <= 3",
            name=op.f("ck_webhook_endpoints_endpoint_active_delivery_count"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_endpoints_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_endpoints")),
        sa.UniqueConstraint(
            "organization_id", "id", name="uq_webhook_endpoints_organization_id_id"
        ),
    )
    op.create_index(
        op.f("ix_webhook_endpoints_organization_id"),
        "webhook_endpoints",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "endpoint_secrets",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "endpoint_id"],
            ["webhook_endpoints.organization_id", "webhook_endpoints.id"],
            name=op.f("fk_endpoint_secrets_organization_id_webhook_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_endpoint_secrets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoint_secrets")),
    )
    op.create_index(
        op.f("ix_endpoint_secrets_endpoint_id"), "endpoint_secrets", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_endpoint_secrets_organization_id"),
        "endpoint_secrets",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_endpoint_secrets_active",
        "endpoint_secrets",
        ["endpoint_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "endpoint_subscriptions",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "endpoint_id"],
            ["webhook_endpoints.organization_id", "webhook_endpoints.id"],
            name=op.f("fk_endpoint_subscriptions_organization_id_webhook_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_endpoint_subscriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoint_subscriptions")),
        sa.UniqueConstraint(
            "endpoint_id", "event_type", name=op.f("uq_endpoint_subscriptions_endpoint_id")
        ),
    )
    op.create_index(
        op.f("ix_endpoint_subscriptions_endpoint_id"),
        "endpoint_subscriptions",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_endpoint_subscriptions_organization_id"),
        "endpoint_subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("api_key_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canonical_body", sa.LargeBinary(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version >= 1 AND version <= 32767", name=op.f("ck_events_event_version")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "api_key_id"],
            ["api_keys.organization_id", "api_keys.id"],
            name=op.f("fk_events_organization_id_api_keys"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "organization_id",
            "api_key_id",
            "idempotency_key",
            name="uq_events_organization_key_idempotency",
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_events_organization_id_id"),
    )
    op.create_index(op.f("ix_events_api_key_id"), "events", ["api_key_id"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replay_of", sa.String(length=36), nullable=True),
        sa.Column("replay_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','queued','delivering','retry_scheduled',"
            "'succeeded','dead_lettered','cancelled')",
            name=op.f("ck_deliveries_delivery_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND attempt_count <= 6",
            name=op.f("ck_deliveries_delivery_attempt_count"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "endpoint_id"],
            ["webhook_endpoints.organization_id", "webhook_endpoints.id"],
            name=op.f("fk_deliveries_organization_id_webhook_endpoints"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["events.organization_id", "events.id"],
            name=op.f("fk_deliveries_organization_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "replay_of"],
            ["deliveries.organization_id", "deliveries.id"],
            name=op.f("fk_deliveries_organization_id_deliveries"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_deliveries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("organization_id", "id", name="uq_deliveries_organization_id_id"),
    )
    op.create_index(op.f("ix_deliveries_endpoint_id"), "deliveries", ["endpoint_id"], unique=False)
    op.create_index(op.f("ix_deliveries_event_id"), "deliveries", ["event_id"], unique=False)
    op.create_index(op.f("ix_deliveries_lease_until"), "deliveries", ["lease_until"], unique=False)
    op.create_index(
        op.f("ix_deliveries_next_attempt_at"), "deliveries", ["next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_organization_id"), "deliveries", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_deliveries_replay_of"), "deliveries", ["replay_of"], unique=False)
    op.create_index(op.f("ix_deliveries_status"), "deliveries", ["status"], unique=False)
    op.create_index(
        "uq_deliveries_original_event_endpoint",
        "deliveries",
        ["event_id", "endpoint_id"],
        unique=True,
        postgresql_where=sa.text("replay_of IS NULL"),
    )
    op.create_index(
        "uq_deliveries_replay_idempotency",
        "deliveries",
        ["organization_id", "replay_of", "replay_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("replay_of IS NOT NULL"),
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("delivery_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("preview_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("preview_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("preview_key_version", sa.Integer(), nullable=True),
        sa.Column("retry_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('started','succeeded','failed','unknown')",
            name=op.f("ck_delivery_attempts_attempt_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "delivery_id"],
            ["deliveries.organization_id", "deliveries.id"],
            name=op.f("fk_delivery_attempts_organization_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_delivery_attempts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_attempts")),
        sa.UniqueConstraint(
            "delivery_id", "attempt_number", name=op.f("uq_delivery_attempts_delivery_id")
        ),
    )
    op.create_index(
        op.f("ix_delivery_attempts_delivery_id"), "delivery_attempts", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_attempts_organization_id"),
        "delivery_attempts",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_attempts_organization_id"), table_name="delivery_attempts")
    op.drop_index(op.f("ix_delivery_attempts_delivery_id"), table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index(
        "uq_deliveries_replay_idempotency",
        table_name="deliveries",
        postgresql_where=sa.text("replay_of IS NOT NULL"),
    )
    op.drop_index(
        "uq_deliveries_original_event_endpoint",
        table_name="deliveries",
        postgresql_where=sa.text("replay_of IS NULL"),
    )
    op.drop_index(op.f("ix_deliveries_status"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_replay_of"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_organization_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_next_attempt_at"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_lease_until"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_event_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_endpoint_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_api_key_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        op.f("ix_endpoint_subscriptions_organization_id"), table_name="endpoint_subscriptions"
    )
    op.drop_index(
        op.f("ix_endpoint_subscriptions_endpoint_id"), table_name="endpoint_subscriptions"
    )
    op.drop_table("endpoint_subscriptions")
    op.drop_index(
        "uq_endpoint_secrets_active",
        table_name="endpoint_secrets",
        postgresql_where=sa.text("active"),
    )
    op.drop_index(op.f("ix_endpoint_secrets_organization_id"), table_name="endpoint_secrets")
    op.drop_index(op.f("ix_endpoint_secrets_endpoint_id"), table_name="endpoint_secrets")
    op.drop_table("endpoint_secrets")
    op.drop_index(op.f("ix_webhook_endpoints_organization_id"), table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_api_keys_organization_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_index(op.f("ix_outbox_messages_topic"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_status"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_lease_until"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_available_at"), table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_aggregate_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_table("organizations")
    # ### end Alembic commands ###
