from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class IdentityRepository(Protocol):
    async def user_by_email(self, email: str) -> Any | None: ...

    async def user_by_id(self, user_id: str) -> Any | None: ...

    async def create_registration(
        self, email: str, password_hash: str, organization_name: str
    ) -> tuple[Any, Any, Any]: ...

    async def create_refresh(
        self, user_id: str, family_id: str, digest: str, expires_at: datetime
    ) -> Any: ...

    async def refresh_by_hash_for_update(self, digest: str) -> Any | None: ...

    async def revoke_refresh(self, token: Any, replaced_by_id: str | None = None) -> None: ...

    async def revoke_family(self, family_id: str) -> None: ...

    async def memberships(self, user_id: str) -> list[Any]: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
